server {
    listen 80;
    server_name localhost;
    
    # Logs pour le débogage
    error_log /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;
    
    # Serve static files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend
    location /api/ {
        # IMPORTANT: Ne pas ajouter de /api/ à la fin de proxy_pass
        # car cela doublerait le préfixe /api
        proxy_pass http://detectish-backend:3000;
        
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
        add_header Referrer-Policy "strict-origin-when-cross-origin";
    }
}