services:
  detectish:
    image: matthl2002/detectish:latest
    container_name: detectish
    depends_on:
      - mysql
      - clamav
    networks:
      - detectish-network
    volumes:
      - ./phishing_email_example:/app/phishing_email_example
    environment:
      DB_NAME: detectish_db
      DB_USER: detectish_user
      DB_PASSWORD: detectish_password
      DB_HOST: mysql
      DB_PORT: 3306
      CLAMAV_HOST: clamav
      CLAMAV_PORT: 3310

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    ports:
      - "3310:3310" 
    networks:
      - detectish-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: detectish_db
      MYSQL_USER: detectish_user
      MYSQL_PASSWORD: detectish_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - detectish-network
    ports:
      - "3306:3306"

volumes:
  mysql-data:

networks:
  detectish-network:
    driver: bridge
