services:
  detectish:
    image: matthl2002/detectish:latest
    container_name: detectish
    depends_on:
      mysql:
        condition: service_healthy
      clamav:
        condition: service_started
    networks:
      - detectish-network
    volumes:
      - ./phishing_email_example:/app/phishing_email_example
    environment:
      DB_NAME: detectish_db
      DB_USER: detectish_user
      DB_PASSWORD: detectish_password
      DB_HOST: mysql
      DB_PORT: 3306
      CLAMAV_HOST: clamav
      CLAMAV_PORT: 3310

  backend:
    build: 
      context: ./backend
    container_name: detectish-backend
    hostname: detectish-backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      detectish:
        condition: service_started
    networks:
      - detectish-network
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: detectish_user
      DB_PASSWORD: detectish_password
      DB_NAME: detectish_db
      DB_PORT: 3306
      JWT_SECRET: ${JWT_SECRET:-your_secure_random_string_here}
    ports:
      - "3000:3000"

  frontend:
    build: 
      context: ./frontend
    container_name: detectish-frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - detectish-network
    ports:
      - "80:80"

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    ports:
      - "3310:3310" 
    networks:
      - detectish-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: detectish_db
      MYSQL_USER: detectish_user
      MYSQL_PASSWORD: detectish_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - detectish-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "detectish_user", "--password=detectish_password"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  mysql-data:

networks:
  detectish-network:
    driver: bridge
