import subprocess
import os
import json
from dotenv import load_dotenv

try:
    from mistralai import Mistral
except Exception:
    Mistral = None

# Load environment variables from .env file if available
# (useful for local development)
load_dotenv()

def send_curl_requests(filename):
    directory = 'phishing_email_example'
    url = 'http://0.0.0.0:6969/analyse'

    file_path = os.path.join(directory, filename)
    result = subprocess.run([
        'curl', '-X', 'POST', url, '-F', f'file=@{file_path}'
    ], capture_output=True, text=True)
    return result.stdout 

def generate_explanation(email_data):
    """
    Generates a structured explanation for an email using Mistral
    
    Args:
        email_data (dict): Complete email data and its analysis
        
    Returns:
        str: The explanation generated by Mistral
    """
    try:
        model = "mistral-large-latest"

        if Mistral is None:
            return "Mistral explanation is temporarily unavailable because the Mistral SDK could not be loaded in this environment."

        # Get API key from environment variables
        api_key = os.environ.get("MISTRAL_API_KEY")
        if not api_key:
            raise ValueError("Mistral API key is not configured in environment variables")
            
        client = Mistral(api_key=api_key)
        
        # Extract and organize important information for analysis
        organized_data = {
            "email": {
                "subject": email_data.get("subject") or "No subject",
                "sender": email_data.get("sender") or "Unknown",
                "receiver": email_data.get("user", {}).get("email") or "Unknown",
                "date": email_data.get("receivedDate") or "Unknown",
                "status": email_data.get("status") or "Unknown"
            },
            "analysis": {
                "spf": next((a.get("result") for a in email_data.get("analyses", []) if a.get("type") == "SPF"), "Unknown"),
                "dkim": next((a.get("result") for a in email_data.get("analyses", []) if a.get("type") == "DKIM"), "Unknown"),
                "dmarc": next((a.get("result") for a in email_data.get("analyses", []) if a.get("type") == "DMARC"), "Unknown"),
                "malware_scan": next((a.get("result") for a in email_data.get("analyses", []) if a.get("type") == "CLAMAV"), "Unknown"),
                "phishing_score": next((a.get("result") for a in email_data.get("analyses", []) if a.get("type") == "AI"), "Unknown"),
                "urls": [link.get("url") for link in email_data.get("links", [])]
            }#,
            #"detailed_analysis": email_data.get("analysis") or email_data.get("analyse_details") or []
        }
        
        # Convert organized data to JSON for the prompt
        analysis_json = json.dumps(organized_data, indent=2, ensure_ascii=False)
        
        # Build a richer and structured prompt
        system_prompt = """
You are a cybersecurity expert explaining in simple English why an email was filtered. 
Your mission is to analyze the technical data and explain clearly and accessibly why the email was considered suspicious.

Here is the structure of the data you will analyze:
- email: basic information about the email (sender, receiver, subject, date)
- analysis: results of various security analyses (SPF, DKIM, DMARC, antivirus scan, phishing score)
- detailed_analysis: additional detailed analyses

Rules to follow:
1. Your explanation must be clear and understandable for non-experts
2. Identify the main security issues detected
3. Explain why these issues are concerning
4. If the information is insufficient, indicate it clearly
5. Use a structured format with titles and subtitles
6. Avoid technical jargon unless you explain it
        """
        
        # Prepare messages for Mistral
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "system", "content": f"Here is the email data to analyze: {analysis_json}"},
            {"role": "user", "content": "Why was this email filtered? Explain the detected security issues clearly and precisely."}
        ]
        
        # Call Mistral API
        chat_response = client.chat.complete(
            model=model,
            messages=messages,
            max_tokens=2000
        )
        
        # Return the response
        explanation = chat_response.choices[0].message.content
        
        # If the explanation is too generic, add a warning
        if "I don't have enough information" in explanation.lower() or "missing information" in explanation.lower():
            explanation += "\n\n---\n\n**Technical Note**: The data provided for the analysis was insufficient or incomplete. Ensure that all security analyses are properly configured and available."
            
        return explanation
    except Exception as e:
        print(f"An error occurred while calling Mistral: {e}")
        return f"Unable to generate an explanation for this email. Error: {str(e)}"

def answer(filename):
    try:
        email_data = json.loads(send_curl_requests(filename))
        explanation = generate_explanation(email_data)
        print(explanation)
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == '__main__':
    filename="test_SPF.eml"
    print(send_curl_requests(filename))
    answer(filename)
